/**
 * ForgeSchool — icon generator
 *
 * Walks `src/lib/icons/raw/` for `.svg` files and emits a typed Svelte 5
 * component per icon into `src/lib/icons/generated/`. Run via:
 *
 *     pnpm icons:generate
 *
 * Generated components are committed to the repo — they are source, not
 * build artifacts. This is a deliberate PE7 choice: icon output is
 * reviewed in PRs, and the emitted Svelte is what components import.
 *
 * The generator is intentionally small (< 120 lines). Emitted components
 * accept:
 *   - size?: number | string     (CSS size; defaults to '1em')
 *   - class?: string             (extra classes merged with the SVG root)
 *   - title?: string             (accessible title; omitted if absent)
 *
 * Colors always inherit via stroke="currentColor" / fill="currentColor".
 * The raw SVG is expected to already use currentColor — this script does
 * not transform color attributes. If a raw SVG has hardcoded colors, fix
 * it at the source, not in the generator.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { basename, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const RAW_DIR = join(ROOT, 'src/lib/icons/raw');
const OUT_DIR = join(ROOT, 'src/lib/icons/generated');

type RawIcon = {
	name: string;
	pascalName: string;
	viewBox: string;
	inner: string;
};

function toPascalCase(name: string): string {
	return name
		.split(/[-_\s]+/)
		.filter((segment): segment is string => segment.length > 0)
		.map((segment) => segment[0]!.toUpperCase() + segment.slice(1).toLowerCase())
		.join('');
}

function parseSvg(source: string): { viewBox: string; inner: string } {
	const openTagMatch = source.match(/<svg\b[^>]*>/i);
	if (!openTagMatch) {
		throw new Error('Missing <svg> opening tag');
	}
	const viewBoxMatch = openTagMatch[0].match(/viewBox="([^"]+)"/i);
	if (!viewBoxMatch) {
		throw new Error('Missing viewBox attribute on <svg>');
	}
	const openEnd = openTagMatch.index! + openTagMatch[0].length;
	const closeStart = source.lastIndexOf('</svg>');
	if (closeStart < 0) {
		throw new Error('Missing </svg> closing tag');
	}
	const viewBox = viewBoxMatch[1]!;
	const inner = source.slice(openEnd, closeStart).trim();
	return { viewBox, inner };
}

function renderComponent({ pascalName, viewBox, inner }: RawIcon): string {
	const indentedInner = inner
		.split('\n')
		.map((line) => (line.trim() === '' ? '' : `\t${line.trim()}`))
		.join('\n');

	return `<!-- Auto-generated by scripts/generate-icons.ts. Do not edit by hand. -->
<script lang="ts">
	type Props = {
		size?: number | string;
		class?: string;
		title?: string;
	};

	let { size = '1em', class: extraClass, title }: Props = $props();
</script>

<svg
	xmlns="http://www.w3.org/2000/svg"
	viewBox="${viewBox}"
	width={size}
	height={size}
	fill="none"
	stroke="currentColor"
	stroke-width="1.75"
	stroke-linecap="round"
	stroke-linejoin="round"
	role={title ? 'img' : 'presentation'}
	aria-label={title ?? undefined}
	aria-hidden={title ? undefined : 'true'}
	class={extraClass}
>
	{#if title}<title>{title}</title>{/if}
${indentedInner}
</svg>
`;
}

async function main(): Promise<void> {
	await mkdir(OUT_DIR, { recursive: true });
	const entries = await readdir(RAW_DIR);
	const svgFiles = entries.filter((name) => extname(name).toLowerCase() === '.svg');

	if (svgFiles.length === 0) {
		console.log(`[generate-icons] no SVGs found in ${RAW_DIR}`);
		return;
	}

	for (const file of svgFiles) {
		const name = basename(file, extname(file));
		const pascalName = toPascalCase(name);
		const source = await readFile(join(RAW_DIR, file), 'utf8');
		const { viewBox, inner } = parseSvg(source);
		const component = renderComponent({ name, pascalName, viewBox, inner });
		const outPath = join(OUT_DIR, `${pascalName}.svelte`);
		await writeFile(outPath, component, 'utf8');
		console.log(`[generate-icons] ${file} -> ${pascalName}.svelte`);
	}

	console.log(`[generate-icons] wrote ${svgFiles.length} component(s) to ${OUT_DIR}`);
}

await main();
